services:
  postgresql:
    image: postgres:17.2
    restart: "no"
    ports:
      - "5432:5432"
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: web_store_app_user
      POSTGRES_PASSWORD: web_store_app_password
      POSTGRES_DB: web_store_db
    healthcheck:
      test: pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB
      interval: 10s
      timeout: 5s
      start_period: 10s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: store_app:latest
    environment:
      SPRING_PROFILES_ACTIVE: prod
    depends_on:
      postgresql:
        condition: service_healthy
    expose:
      - "8080"
    ports:
      - "8080:8080"

volumes:
  postgresql_data:
